[tool.poetry]
name = "ai"
version = "0.1.0"
description = ""
authors = ["Tao Xiao"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
langchain = {extras = ["openai"], version = "^0.3.21"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
